### ISSUE TITLE
Convert to pdf after merge

### ISSUE THREAD

**Issue by dellert** [jupitern/docx#1]
Hi, I merged docx files with that library, and all is OK, but when I wannna convert merged file to pdf, Pdf file  returns broken. For converting I use **unoconv** linux command. 
Could it be a problem in this command? Thanks

**Comment by jupitern** [comment]
Hi,
Does it support convertions to docx?
In unoconv website i cant any reference to .docx files, only .doc. Docx is quite different.

**Comment by dellert** [comment]
Trouble was in LibreOffice. This lib doesn't work correctly with it:)
